In [1]:
import numpy as np
import pandas as pd

1.1 Creating a vector

In [2]:
vector_row = np.array([1,2,3])
vector_row

array([1, 2, 3])

In [6]:
vector_column = np.array([[1],[2],[3]])
vector_column

array([[1],
       [2],
       [3]])

1.2 Creating a matrix

In [7]:
matrix = np.array([[1,2],[1,2],[1,2]])
matrix

array([[1, 2],
       [1, 2],
       [1, 2]])

In [10]:
matrix_object = np.mat([[1,2],[1,2],[1,2]])
matrix_object

matrix([[1, 2],
        [1, 2],
        [1, 2]])

1.3 Creating a sparse matrix

Sparse matrices only store non-zero values.
in CSR matrices, the values in the sparse matrix are the zero-indexed row and column number indices of the non-zero values in the matrix.
for example, the sparse matrix of the two matrices below is [[1,1],[2,0]] the [1,1] says that there is a non-zero element('1') is in the 2nd row and 2nd column, and a non-zero element('3') is in the 3rd row and 1st column. The row and column numbers subtracted by one to account for zero-indexed scheme would yield the aforementioned sparse matrix.

In [3]:
from scipy import sparse
matrix = np.array([[0,0],[0,1],[3,0]])
print(matrix)

[[0 0]
 [0 1]
 [3 0]]


In [4]:
# Compressed sparse row(CSR)
matrix_sparse = sparse.csr_matrix(matrix)
print(matrix_sparse)

  (1, 1)	1
  (2, 0)	3


In [ ]:
# Adding zeros does not affect the shape of the sparse matrix
matrix = np.array([[0,0,0,0,0,0,0,0,0],
                   [0,1,0,0,0,0,0,0,0],
                   [3,0,0,0,0,0,0,0,0]])
# Compressed sparse row(CSR)
matrix_sparse = sparse.csr_matrix(matrix)
print(matrix_sparse)

1.4 Selecting elements

In [21]:
vector = np.array([1,2,3,4,5,6])
vector

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
vector[2]

3

In [23]:
#Select all elements of vector
vector[:]

array([1, 2, 3, 4, 5, 6])

In [ ]:
#Select everything up to and including third element
vector[:3]

In [26]:
#Select everything after the third element
vector[3:]

array([4, 5, 6])

In [27]:
#Select the last element
vector[-1]

6

In [30]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
matrix[1,1]

5

In [33]:
#Select the 1st two rows and all columns of a matrix
matrix[:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
#Select all rows and the 2nd column of a matrix
matrix[:,1:2]


array([[2],
       [5],
       [8]])

In [35]:
#Select all rows and the 1st two columns of a matrix
matrix[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [37]:
#Select all but last column of a matrix
matrix[:,:-1]

array([[1, 2],
       [4, 5],
       [7, 8]])

1.5 Describing a matrix

In [10]:
matrix = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
matrix

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [9]:
matrix.shape

(3, 4)

In [44]:
matrix.size

12

In [45]:
# Number of dimensions
matrix.ndim

2

1.6 Applying operations to elements

In [54]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
add_100 = lambda i: i +100

In [56]:
vectorized_add_100 = np.vectorize(add_100)

In [57]:
vectorized_add_100(matrix)

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [58]:
vectorized_add_100

In [59]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [60]:
# simpler version of broadcasting(applying a function on ALL or part(slice) of arrays
matrix + 100

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [61]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [62]:
matrix1 = matrix + 100
print(matrix1)

[[101 102 103]
 [104 105 106]
 [107 108 109]]


In [63]:
matrix2 = matrix * 100
print(matrix2)

[[100 200 300]
 [400 500 600]
 [700 800 900]]


1.7 Finding maximum and minimum values

In [64]:
np.max(matrix)

9

In [65]:
np.min(matrix)


1

1.8 Calculating the average, variance, and standard deviation

In [ ]:
np.mean(matrix)

In [72]:
# Find the mean value in each column
np.mean(matrix, axis=0)


array([4., 5., 6.])

In [70]:
np.var(matrix)

6.666666666666667

In [ ]:
np.std(matrix)

1.9 Reshaping arrays

In [74]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
matrix.shape

(4, 3)

In [75]:
matrix.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [76]:
matrix

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

1.10 Transposing a vector or matrix

In [77]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [78]:
# Columns become rows and rows become columns
matrix.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [79]:
# transposing a vector affect the order of values but it does convert a row vector to a column vector
np.array([1,2,3,4,5,6]).T

array([1, 2, 3, 4, 5, 6])

In [84]:
# Transpose a row vector
row_vector = np.array([[1,2,3,4,5,6]])
row_vector.T

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

1.11 Flattening a matrix

In [85]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [86]:
matrix.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [87]:
# Another way to flatten a matrix
matrix.reshape(1,-1)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

1.12 Finding the rank of a matrix
The Rank of a matrix is the dimensions of the vector space spanned by it columns or rows.

In [90]:
matrix = np.array([[1,1,1],[1,1,10],[1,1,15]])
matrix

array([[ 1,  1,  1],
       [ 1,  1, 10],
       [ 1,  1, 15]])

In [91]:
np.linalg.matrix_rank(matrix)

2

In [92]:
np.linalg.matrix_power()

TypeError: _matrix_power_dispatcher() missing 1 required positional argument: 'n'

1.13 Calculating determinant

In [94]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [95]:
np.linalg.det(matrix)
#

6.66133814775094e-16

1.14 Getting the diagonal of a matrix

In [108]:
matrix = np.array([[1,2,3],[2,4,6],[3,8,9]])
matrix

array([[1, 2, 3],
       [2, 4, 6],
       [3, 8, 9]])

In [109]:
matrix.diagonal()

array([1, 4, 9])

In [110]:
# Returns diagonal with one above the main diagonal
matrix.diagonal(offset=1)

array([2, 6])

In [111]:
# Returns diagonal with one below the main diagonal
matrix.diagonal(offset=-1)

array([2, 8])

1.15 Calculating the trace of a matrix
The trace of a matrix is the sum of the diagonal elements and is often used under the hood in machine learning methods.

In [112]:
matrix.trace()

14

In [115]:
# Another way to calculate trace
sum(matrix.diagonal())

14

1.16 Finding the Eigenvalues and Eigenvectors

In [121]:
matrix=np.array([[1,-1,3],[1,1,6],[3,8,9]])
eigenvalues, eigenvectors = np.linalg.eig(matrix)

In [122]:
eigenvalues

array([13.55075847,  0.74003145, -3.29078992])

In [123]:
eigenvectors

array([[-0.17622017, -0.96677403, -0.53373322],
       [-0.435951  ,  0.2053623 , -0.64324848],
       [-0.88254925,  0.15223105,  0.54896288]])

1.17 Caclculating dot products

In [124]:
vector_a = np.array([1,2,3])
vector_b = np.array([4,5,6])

In [125]:
# dot product = 1*4 + 2*5 + 3*6 = 4 +10+18 = 32
np.dot(vector_a,vector_b)

32

In [126]:
# Another way in python 3.5+
vector_a @ vector_b

32

1.18 Adding and subtracting matirces

In [127]:
matrix_a = np.array([[1,1,1],[1,1,2],[1,1,2]])
matrix_b = np.array([[1,3,1],[1,3,1],[1,3,8]])

In [128]:
np.add(matrix_a,matrix_b)

array([[ 2,  4,  2],
       [ 2,  4,  3],
       [ 2,  4, 10]])

In [130]:
np.subtract(matrix_a,matrix_b)

array([[ 0, -2,  0],
       [ 0, -2,  1],
       [ 0, -2, -6]])

In [132]:
# or
matrix_a + matrix_b

array([[ 2,  4,  2],
       [ 2,  4,  3],
       [ 2,  4, 10]])

1.19 Multiplying matrices

In [133]:
matrix_a = np.array([[1,1],[1,2]])
matrix_b = np.array([[1,3],[1,2]])

In [134]:
np.dot(matrix_a,matrix_b)

array([[2, 5],
       [3, 7]])

In [138]:
# or
matrix_a @ matrix_b

array([[2, 5],
       [3, 7]])

In [137]:
# element-wise multiplication(i.e. a11 * b11,a12*b12, etc.)
matrix_a * matrix_b


array([[1, 3],
       [1, 4]])

1.20 Inverting a matrix

In [148]:
matrix = np.array([[1,4],[2,5]])

In [151]:
matrix_inv = np.linalg.inv(matrix)
matrix_inv

array([[-1.66666667,  1.33333333],
       [ 0.66666667, -0.33333333]])

In [152]:
matrix_identity = np.dot(matrix,matrix_inv)
matrix_identity

array([[1., 0.],
       [0., 1.]])

In [154]:
np.dot(matrix,matrix_identity)

array([[1., 4.],
       [2., 5.]])

1.21 Generating random values

In [6]:
# set seed
np.random.seed(0)

In [7]:
# Generate three random floats between 0.0 and 1.0
np.random.random(3)

array([0.5488135 , 0.71518937, 0.60276338])

In [159]:
# Generate three random integers between 1 and 10
np.random.randint(0, 11, 3)


array([3, 7, 9])

In [160]:
# Draw three numbers from a normal distribution with mean 0.0
# and standard deviation of 1.0
np.random.normal(0.0, 1.0, 3)


array([-1.42232584,  1.52006949, -0.29139398])

In [161]:
# Draw three numbers from a logistic distribution with mean 0.0 and scale of 1.0
np.random.logistic(0.0, 1.0, 3) 

# Draw three numbers greater than or equal to 1.0 and less than 2.0
np.random.uniform(1.0, 2.0, 3)

In [162]:
# set seed
np.random.seed(10)

In [163]:
# Generate three random floats between 0.0 and 1.0
np.random.random(3)

array([0.77132064, 0.02075195, 0.63364823])

In [164]:
# Generate three random integers between 1 and 10
np.random.randint(0, 11, 3)


array([9, 0, 1])

In [165]:
# Draw three numbers from a normal distribution with mean 0.0
# and standard deviation of 1.0
np.random.normal(0.0, 1.0, 3)


array([-1.01706365,  0.90762422, -0.68212385])

In [166]:
# Draw three numbers from a logistic distribution with mean 0.0 and scale of 1.0
np.random.logistic(0.0, 1.0, 3) 

array([1.89081653, 1.19812181, 1.03061665])

In [167]:
# Draw three numbers greater than or equal to 1.0 and less than 2.0
np.random.uniform(1.0, 2.0, 3)

array([1.87761494, 1.72743551, 1.54088093])