# Data Preprocessing Tools

## Importing the libraries

In [62]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [63]:
dataset = pd.read_csv('Data/DirectMarketing_Cln.csv')

print(dataset)




     Salary  Children  Catalogs  Age_Old  Age_Young  Gender_Male  \
0     47500         0         6        1          0            0   
1     63600         0         6        0          0            1   
2     13500         0        18        0          1            0   
3     85600         1        18        0          0            1   
4     68400         0        12        0          0            0   
..      ...       ...       ...      ...        ...          ...   
995   19400         1        18        0          1            0   
996   40500         1        18        0          0            1   
997   44800         0        24        1          0            1   
998   79000         2        18        0          0            1   
999   53600         1        24        0          1            1   

     OwnHome_Rent  Married_Single  Location_Far  History_Low  History_Medium  \
0               0               1             1          0.0             0.0   
1               1      

In [70]:
X = dataset.iloc[:, :-1].values
y = dataset['AmountSpent'].values

In [71]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X)
X = imputer.transform(X)

In [72]:
print(X)

[[4.75e+04 0.00e+00 6.00e+00 ... 1.00e+00 0.00e+00 0.00e+00]
 [6.36e+04 0.00e+00 6.00e+00 ... 0.00e+00 0.00e+00 0.00e+00]
 [1.35e+04 0.00e+00 1.80e+01 ... 1.00e+00 0.00e+00 0.00e+00]
 ...
 [4.48e+04 0.00e+00 2.40e+01 ... 0.00e+00 0.00e+00 0.00e+00]
 [7.90e+04 2.00e+00 1.80e+01 ... 1.00e+00 0.00e+00 0.00e+00]
 [5.36e+04 1.00e+00 2.40e+01 ... 1.00e+00 0.00e+00 0.00e+00]]


In [73]:
print(y)

[ 755 1318  296 2436 1304  495  782 1155  158 3034  927 2065  704 2136
 5564 2766 3010 1956  542  410  194  827 2328  808  521  655  707 2075
  769  774  573 2082 2446 2636 2226  183 1595  584  982  576  410 3082
 2437 3655  844 2510  983 1215 2000 2574 1116 3604 3360  530  906 2764
 1263 1084 1051  614  704  449  136  468  565 1310 2595  358 1424 4182
  468 2924  964  615   38 1006  307 1648  220  280 1647  704  920  258
 1821 1587  528  867  643  107 1513 4558  741  805  470  278 1093  470
 1856 1688  708 1753 3044  855  550 2265 2452 1184 2150 1575 1822 1153
 1877  450  873  209 1472 1702 1857  451  344 1492 2098 3505  127  436
 2524  189  607  202 1554  633  176 3079 2038 1203  326  235 3688  332
  143 3104 2339  123  879  498 3596 2925 1081  312 1297  218 4279 1642
  581  223  474 1790  143 3237 2316  458  646 1217  238 1293 2749 2408
 2624 4894  621  701  780 1365 2693 1582  724  830 1594 1826  473 1161
  703 1892  489 1813 1457  292  613 2681  437  708 1093  213  202 1298
 3273 

## Splitting the dataset into the Training set and Test set

In [75]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [76]:
print(X_train)

[[3.96e+04 0.00e+00 1.20e+01 ... 1.00e+00 0.00e+00 0.00e+00]
 [1.76e+04 0.00e+00 6.00e+00 ... 1.00e+00 0.00e+00 0.00e+00]
 [3.32e+04 1.00e+00 6.00e+00 ... 1.00e+00 0.00e+00 0.00e+00]
 ...
 [9.65e+04 0.00e+00 2.40e+01 ... 0.00e+00 0.00e+00 1.00e+00]
 [6.87e+04 0.00e+00 2.40e+01 ... 0.00e+00 1.00e+00 0.00e+00]
 [4.70e+04 1.00e+00 1.20e+01 ... 1.00e+00 0.00e+00 0.00e+00]]


In [77]:
print(X_test)

[[5.24e+04 0.00e+00 1.80e+01 ... 1.00e+00 0.00e+00 0.00e+00]
 [9.24e+04 1.00e+00 6.00e+00 ... 0.00e+00 0.00e+00 0.00e+00]
 [5.01e+04 1.00e+00 1.80e+01 ... 0.00e+00 0.00e+00 0.00e+00]
 ...
 [3.82e+04 0.00e+00 6.00e+00 ... 1.00e+00 0.00e+00 0.00e+00]
 [6.05e+04 3.00e+00 1.20e+01 ... 1.00e+00 0.00e+00 0.00e+00]
 [2.67e+04 1.00e+00 1.20e+01 ... 1.00e+00 0.00e+00 0.00e+00]]


In [78]:
print(y_train)

[ 610  273  320 1215  491  984  410 3916 3398 1932  205 1553  517 1694
  556  858  301  830  850  704 2502 1804  735 1271  239 1861 1184  563
  405  225 1688  222 2290  268  989  548  193  227 1161  704  981 1587
  472  836  365  307  421 1631 1203 1213 1615 2316  143  348 1073  163
  869 2844 1418 1481 1492 1521  292 3010  747 1140  859 1474 1473 2452
  500  808  690 4182  403 2340 2034 1025  624  607 1001 2145   38  856
 1608 1634 1138 1822  466  700  414 1813 2840 1325 2004 1029  865  449
  297   79  639 1009 1087  541  486 1156  472 2038  535  421 2098 1084
 2104 1512 2644 1041  731  983  847  871  645 1102 1786 2492  755  858
 1431 2595 5151  438 2177 2784  659 1085  349 4984 1926  536  458  381
  424 1853  210  883 1634  342 1237  770  759 1476  741  873 1651 1800
  307  514 3671  176  661 3537 1051  183 2243 1081 1344  410  107 1093
  157 1424  932  587  332  748  486 1857 1850 1024 1351  657  975  880
  613 1042  865 5564 1227  920  166 1307  534  636  643 1255  719  780
 1280 

In [79]:
print(y_test)

[ 857 2191 1071  983 1485 1634  917 1120  821 2574 1437 2339 2279  616
 1047 3079  550  782  909 5878 1355 1781 1398  417  314  451 2150  863
 1322  617  791 1905  197 1021 3941 1308  220 2610  788  160  947 1011
 1513 1753  470  619  260 3082 1699  384  654 2226 1594  183 1081  567
 1197  630 1666 1384 2070  690  881 1757  824 2904 2710   65  245 1956
  216 2224 1512  606  173 1310  708 1523  915  422 1789  705  907  445
  529  941  409  642  794  170  358 2681  753 1685  192  841  164  191
 2183  581 1012 2136 1473  474  788  167 3293 1414 1560  395  233  954
  422  614  929 1582  163 2632  344  195  473 2321 2436  202  902 2935
 3168 2561 1821 1062  586 1654  206  296 1417 1320 2523 2318 3063 1500
  615 1702 1773 1944 1153  371 2090  269 2107  491  448  510  158 3126
 1263 2838 2840 1408 1821  774 3237  202  436 1611 2258  418 1165  919
 1566 1298 1721  704  438 1699  392 1985 1457  968  172 2177 5830 1116
  550  737   47 1186 3491 1583  322 1692  180 1332 2479 2491  754 1985
  757 

## Feature Scaling

In [80]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [81]:
print(X_train)

[[-0.5276 -0.8817 -0.3956 ...  0.9512 -0.2924 -0.1382]
 [-1.2502 -0.8817 -1.3025 ...  0.9512 -0.2924 -0.1382]
 [-0.7378  0.0664 -1.3025 ...  0.9512 -0.2924 -0.1382]
 ...
 [ 1.3415 -0.8817  1.4181 ... -1.0513 -0.2924  7.2342]
 [ 0.4283 -0.8817  1.4181 ... -1.0513  3.4203 -0.1382]
 [-0.2845  0.0664 -0.3956 ...  0.9512 -0.2924 -0.1382]]


In [82]:
print(X_test)


[[-0.1071 -0.8817  0.5112 ...  0.9512 -0.2924 -0.1382]
 [ 1.2069  0.0664 -1.3025 ... -1.0513 -0.2924 -0.1382]
 [-0.1826  0.0664  0.5112 ... -1.0513 -0.2924 -0.1382]
 ...
 [-0.5735 -0.8817 -1.3025 ...  0.9512 -0.2924 -0.1382]
 [ 0.159   1.9625 -0.3956 ...  0.9512 -0.2924 -0.1382]
 [-0.9513  0.0664 -0.3956 ...  0.9512 -0.2924 -0.1382]]


## Training the Multiple Linear Regression model on the Training set

In [83]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

## Predicting the Test set results

In [84]:
y_pred = regressor.predict(X_test)

In [85]:
len(X_test)

200

## Evaluating results

In [88]:
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[ 857.  857.]
 [2191. 2191.]
 [1071. 1071.]
 [ 983.  983.]
 [1485. 1485.]
 [1634. 1634.]
 [ 917.  917.]
 [1120. 1120.]
 [ 821.  821.]
 [2574. 2574.]
 [1437. 1437.]
 [2339. 2339.]
 [2279. 2279.]
 [ 616.  616.]
 [1047. 1047.]
 [3079. 3079.]
 [ 550.  550.]
 [ 782.  782.]
 [ 909.  909.]
 [5878. 5878.]
 [1355. 1355.]
 [1781. 1781.]
 [1398. 1398.]
 [ 417.  417.]
 [ 314.  314.]
 [ 451.  451.]
 [2150. 2150.]
 [ 863.  863.]
 [1322. 1322.]
 [ 617.  617.]
 [ 791.  791.]
 [1905. 1905.]
 [ 197.  197.]
 [1021. 1021.]
 [3941. 3941.]
 [1308. 1308.]
 [ 220.  220.]
 [2610. 2610.]
 [ 788.  788.]
 [ 160.  160.]
 [ 947.  947.]
 [1011. 1011.]
 [1513. 1513.]
 [1753. 1753.]
 [ 470.  470.]
 [ 619.  619.]
 [ 260.  260.]
 [3082. 3082.]
 [1699. 1699.]
 [ 384.  384.]
 [ 654.  654.]
 [2226. 2226.]
 [1594. 1594.]
 [ 183.  183.]
 [1081. 1081.]
 [ 567.  567.]
 [1197. 1197.]
 [ 630.  630.]
 [1666. 1666.]
 [1384. 1384.]
 [2070. 2070.]
 [ 690.  690.]
 [ 881.  881.]
 [1757. 1757.]
 [ 824.  824.]
 [2904. 2904.]
 [2710. 27

In [50]:
print(np.concatenate((y_test.reshape(len(y_test),1), y_pred.reshape(len(y_pred),1)),1))

[[ 857.     1472.9237]
 [2191.     1956.6989]
 [1071.     1702.4144]
 [ 983.     1214.9737]
 [1485.     2305.415 ]
 [1634.     1677.6885]
 [ 917.     1549.4125]
 [1120.      960.4538]
 [ 821.     1264.4437]
 [2574.     2172.0921]
 [1437.     2051.5607]
 [2339.     2913.4965]
 [2279.     2216.2819]
 [ 616.      228.2583]
 [1047.      731.1   ]
 [3079.     2148.0301]
 [ 550.      810.5894]
 [ 782.      766.0238]
 [ 909.      685.3365]
 [5878.     3266.8891]
 [1355.     1339.3668]
 [1781.     1843.7492]
 [1398.      911.6911]
 [ 417.      668.3334]
 [ 314.      802.3606]
 [ 451.      507.6164]
 [2150.     2160.7072]
 [ 863.     1788.4191]
 [1322.     1569.0168]
 [ 617.      527.6251]
 [ 791.      522.7884]
 [1905.     1730.0533]
 [ 197.       78.5718]
 [1021.     1187.1471]
 [3941.     2483.7722]
 [1308.     1867.7772]
 [ 220.       -8.8752]
 [2610.     2315.536 ]
 [ 788.     1329.5725]
 [ 160.      226.0763]
 [ 947.     1253.4244]
 [1011.      816.1006]
 [1513.     2009.8817]
 [1753.    

## Training the Logistic Regression model on the Training set

In [60]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [61]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

LogisticRegression(random_state=0)