In [2]:
#Analyzing text for whether comments are positive or negative
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd
import numpy as np

Addr1='DailyComments.csv'
dataframe = pd.read_csv(Addr1)
print(dataframe)
corpus = dataframe['comments']

  Day of Week                                        comments
0      Monday                             Hello, how are you?
1     Tuesday                            Today is a good day!
2   Wednesday  It's my birthday so it's a really special day!
3    Thursday       Today is neither a good day or a bad day!
4      Friday                           I'm having a bad day.
5    Saturday       There' s nothing special happening today.
6      Sunday                      Today is a SUPER good day!


In [3]:
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)

print("vectorized words")
print(vectorizer.get_feature_names())
print("Identify Feature Words - Matrix View")
print( X.toarray())
print("Matrix shape")
print(X.toarray().shape)

vectorized words
['are', 'bad', 'birthday', 'day', 'good', 'happening', 'having', 'hello', 'how', 'is', 'it', 'my', 'neither', 'nothing', 'or', 'really', 'so', 'special', 'super', 'there', 'today', 'you']
Identify Feature Words - Matrix View
[[1 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 1 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 1 1 0 0 0 0 0 0 2 1 0 0 0 1 1 1 0 0 0 0]
 [0 1 0 2 1 0 0 0 0 1 0 0 1 0 1 0 0 0 0 0 1 0]
 [0 1 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 1 0 1 1 0]
 [0 0 0 1 1 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 1 0]]
Matrix shape
(7, 22)


In [4]:
df = pd.DataFrame(X.toarray(),columns=vectorizer.get_feature_names())
df

are  bad  birthday  day  good  happening  having  hello  how  is  ...  \
0    1    0         0    0     0          0       0      1    1   0  ...   
1    0    0         0    1     1          0       0      0    0   1  ...   
2    0    0         1    1     0          0       0      0    0   0  ...   
3    0    1         0    2     1          0       0      0    0   1  ...   
4    0    1         0    1     0          0       1      0    0   0  ...   
5    0    0         0    0     0          1       0      0    0   0  ...   
6    0    0         0    1     1          0       0      0    0   1  ...   

   neither  nothing  or  really  so  special  super  there  today  you  
0        0        0   0       0   0        0      0      0      0    1  
1        0        0   0       0   0        0      0      0      1    0  
2        0        0   0       1   1        1      0      0      0    0  
3        1        0   1       0   0        0      0      0      1    0  
4        0        0   0       0   0        0      0      0      0    0  
5        0        1   0       0   0        1      0      1      1    0  
6        0        0   0       0   0        0      1      0      1    0  

[7 rows x 22 columns]

In [5]:
df = pd.DataFrame({'text' : corpus})
df



text
0                             Hello, how are you?
1                            Today is a good day!
2  It's my birthday so it's a really special day!
3       Today is neither a good day or a bad day!
4                           I'm having a bad day.
5       There' s nothing special happening today.
6                      Today is a SUPER good day!

In [11]:
df = pd.DataFrame({'text' : corpus})
df



text
0                             Hello, how are you?
1                            Today is a good day!
2  It's my birthday so it's a really special day!
3       Today is neither a good day or a bad day!
4                           I'm having a bad day.
5       There' s nothing special happening today.
6                      Today is a SUPER good day!

In [ ]:
#check for positive words and negative words
df['positive1'] = df.text.str.count('good')
df['positive2']= df.text.str.count('special')
df['negative'] = df.text.str.count('bad')
df['TotScore'] = df.positive1 + df.positive2 - df.negative

print("")
print(df)



In [ ]:
Z = sum(df['TotScore'])
print("")
print("Overall Score:  ",Z)


vectorized words

['are', 'bad', 'birthday', 'day', 'good', 'happening', 'having', 'hello', 'how', 'is', 'it', 'my', 'neither', 'nothing', 'or', 'really', 'so', 'special', 'super', 'there', 'today', 'you']

Identify Feature Words - Matrix View

[[1 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 1 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 1 1 0 0 0 0 0 0 2 1 0 0 0 1 1 1 0 0 0 0]
 [0 1 0 2 1 0 0 0 0 1 0 0 1 0 1 0 0 0 0 0 1 0]
 [0 1 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 1 0 1 1 0]
 [0 0 0 1 1 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 1 0]]


In [6]:
df = pd.DataFrame({'text' : corpus})
df



text
0                             Hello, how are you?
1                            Today is a good day!
2  It's my birthday so it's a really special day!
3       Today is neither a good day or a bad day!
4                           I'm having a bad day.
5       There' s nothing special happening today.
6                      Today is a SUPER good day!

In [7]:
#check for positive words and negative words
df['positive1'] = df.text.str.count('good')
df['positive2']= df.text.str.count('special')
df['negative'] = df.text.str.count('bad')
df['TotScore'] = df.positive1 + df.positive2 - df.negative

print("")
print(df)




                                             text  positive1  positive2  \
0                             Hello, how are you?          0          0   
1                            Today is a good day!          1          0   
2  It's my birthday so it's a really special day!          0          1   
3       Today is neither a good day or a bad day!          1          0   
4                           I'm having a bad day.          0          0   
5       There' s nothing special happening today.          0          1   
6                      Today is a SUPER good day!          1          0   

   negative  TotScore  
0         0         0  
1         0         1  
2         0         1  
3         1         0  
4         1        -1  
5         0         1  
6         0         1  


In [8]:
Z = sum(df['TotScore'])
print("")
print("Overall Score:  ",Z)


Overall Score:   3
