In [9]:
import numpy as np

list_1 = [1,2,3]
array_1 = np.array(list_1)

In [10]:
import array as arr
a = arr.array('d',[1.2,3.4,5.6])
print(a)

array('d', [1.2, 3.4, 5.6])


In [11]:
type(array_1)

numpy.ndarray

In [12]:
type(list_1)

list

In [14]:
list_2 = list_1 + list_1
print(list_2)

[1, 2, 3, 1, 2, 3]


In [22]:
array_2 = array_1 + array_1
print(array_2)

[2 4 6]


In [23]:
print("array_1 * array_2 = ", array_1*array_1)

array_1 * array_2 =  [1 4 9]


In [24]:
print("array_1 / array_2 = ", array_1/array_1)

array_1 / array_2 =  [1. 1. 1.]


In [25]:
print("array_1 ** array_2 = ", array_1**array_1)

array_1 ** array_2 =  [ 1  4 27]


In [37]:
list_5 = [i for i in range(1,6)]
print(list_5)

[1, 2, 3, 4, 5]


In [38]:
array_5 = np.array(list_5)
array_5

array([1, 2, 3, 4, 5])

In [39]:
print("Sine:",np.sin(array_5))

Sine: [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


In [40]:
print("Cosine:",np.cos(array_5))

Cosine: [ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]


In [41]:
print("natural logarithm:",np.log(array_5))

natural logarithm: [0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [42]:
print("base-10 logarithm:",np.log10(array_5))

base-10 logarithm: [0.         0.30103    0.47712125 0.60205999 0.69897   ]


In [43]:
print("base-2 logarithm:",np.log2(array_5))

base-2 logarithm: [0.         1.         1.5849625  2.         2.32192809]


In [45]:
print("Exponential:",np.exp(array_5))

Exponential: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [46]:
print("A series of numbers:",np.arange(5,16))


A series of numbers: [ 5  6  7  8  9 10 11 12 13 14 15]


In [47]:
print("Numbers spaced apart by 2: ",np.arange(0,11,2)) 

Numbers spaced apart by 2:  [ 0  2  4  6  8 10]


In [48]:
print("Numbers spaced apart by a floating point number: ",np.arange(0,11,2.5)) 

Numbers spaced apart by a floating point number:  [ 0.   2.5  5.   7.5 10. ]


In [49]:
print("Every 5th number from 30 in reverse order\n",np.arange(30,-1,-5))


Every 5th number from 30 in reverse order
 [30 25 20 15 10  5  0]


In [50]:
print("11 linearly spaced numbers between 1 and 5: ",np.linspace(1,5,11))

11 linearly spaced numbers between 1 and 5:  [1.  1.4 1.8 2.2 2.6 3.  3.4 3.8 4.2 4.6 5. ]


In [52]:
list_2D = [[1,2,3],[4,5,6],[7,8,9]] 
mat1 = np.array(list_2D) 

In [53]:
print("Type/Class of this object:",type(mat1)) 

Type/Class of this object: <class 'numpy.ndarray'>


In [54]:
print("Here is the matrix\n----------\n",mat1,"\n----------")

Here is the matrix
----------
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 
----------


In [56]:
tuple_2D = np.array([(1.5,2,3), (4,5,6)])
print(tuple_2D)

[[1.5 2.  3. ]
 [4.  5.  6. ]]


In [59]:
tuple_3D = np.array([(1.5,2,3), (4,5,6),(7,8,9)])
print(tuple_3D)

[[1.5 2.  3. ]
 [4.  5.  6. ]
 [7.  8.  9. ]]


In [60]:
print("Dimension of this matrix: ",mat1.ndim,sep='')

Dimension of this matrix: 2
